### ISSUE TITLE
Creating a note without title doesn't work

### ISSUE THREAD

**Issue by Sirs0ri** [liamspradlin/Phoebe#1]
The text _"Untitled"_ at the top of the editor generates the impression that the note already has a title, even if it's the default one. Pressing the back-button or the back arrow at the top discards the note though instead of creating it with the default title.
If you want users to add a title, I'd recommend to place the cursor in the title-textbox by default instead of the content-textfield; otherwise _"Untitled"_ should be kept as title.

(Android 6.0.1 // CM13 // Selene 1.0b)

Edit: I came here from a link posted by Francisco in the comments of this post: https://plus.google.com/+FranciscoFranco1990/posts/3hce3VbPFa4, I'm not 100% sure though if this is the correct place to report issues with Selene.

**Comment by franciscofranco** [comment]
How about if we changed the "Untitled" text color to something more subtle, transparent-like? I don't like the idea to automatically open the Keyboard as soon as that activity opens up.

That's some good feedback though, thanks!

**Comment by liamspradlin** [comment]
Alternatively notes could simply be called untitled until the user changes
it. I think that's the easiest option for the user

**Comment by franciscofranco** [comment]
But @liamspradlin we can't have notes with the same title.

**Comment by alarsyo** [comment]
Why not allow to create notes without a title too ? Kind of like Google Keep does. Then pressing the back arrow would delete the note only if text field is empty

**Comment by Sirs0ri** [comment]
I also like the way Keep solved this problem: They use the placeholders  _"Title"_ and _"Note"_ which are clearly identifiable as placeholders and not default values. Furthermore, they allow users to create notes without a title.

Using a using a more precise placeholder than "Untitled" (if you don't want to set a default) or keeping "Untitled" as title unless the user changes it would both be good solutions in my opinion.

**Comment by franciscofranco** [comment]
@Sirs0ri I like your suggestion :+1:
