### ISSUE TITLE
Cards get stuck when deleting a note.

### ISSUE THREAD

**Issue by sapragus** [liamspradlin/Phoebe#5]
When deleting a note, the other cards/notes move back up to take the empty space left by the deleted note, sometimes the animation gets stuck before the cards reach their destination and overlap (see screenshot).

( Tested on a Nexus 5 running stock Android Marshmallow (6.0.1) )
![screenshot_20160317-225754](https://cloud.githubusercontent.com/assets/10344015/13871880/58589a04-ece6-11e5-908b-b869c19a1c76.png)

**Comment by franciscofranco** [comment]
I can't reproduce. Have you tried the latest apk pushed last night?

**Comment by sapragus** [comment]
According to the Play Store I'm running the latest version (1.0b ; I did get an update after installing the app so i think I'm on the latest version)
I can reproduce it easily by creating multiple notes (and I found out it happens also when creating a new one ). 

Here's a video : https://youtu.be/DKq_8u-sId8

Maybe it's my DPI ? I'm using a 420dpi rather than the stock 480 (but I have never encountered issues related to this so I don't think it's the cause as it should be the same thing as the 5X considering the fact it has the same resolution )
If I can provide you with more informations please let me know.

**Comment by franciscofranco** [comment]
I can't reproduce. I just tried, but it never happens. I think it's your custom DPI.
